name: locale_settings
description: A plugin which supports to change the current language on an os level.
version: 1.0.0
homepage:
publish_to: none

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2

flutter:
  plugin:
    platforms:
      android:
        package: com.opdehipt.locale_settings
        pluginClass: LocaleSettingsPlugin
      ios:
        pluginClass: LocaleSettingsPlugin
        sharedDarwinSource: true
      macos:
        pluginClass: LocaleSettingsPlugin
        sharedDarwinSource: true
