name: locale_settings
description: A plugin which supports to change the current language on an os level.
version: 1.0.0
repository: https://github.com/svenopdehipt/locale_settings/tree/main/locale_settings

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.0.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.opdehipt.locale_settings
        pluginClass: LocaleSettingsPlugin
      ios:
        pluginClass: LocaleSettingsPlugin
        sharedDarwinSource: true
      macos:
        pluginClass: LocaleSettingsPlugin
        sharedDarwinSource: true
